- name: requests must be installed
  pip: name=requests state=present

- name: Hight Load Average
  moira_trigger:
    name: "Hight Load Average"
    target: aliasByNode(movingAverage(DevOps.system.*.loadavg.load, '30min'), 2)
    expression: WARN if t1 > {{ ansible_processor_vcpus }} else OK
    tags:
      - Moira
      - Normal

- name: Low Disk Space 
  moira_trigger:
    name: "Low Disk Space"
    target: aliasByNode(DevOps.system.*.disk.*.gigabyte_percentfree, 2, 4)
    warn: 20.0
    error: 5.0
    tags:
      - Moira
      - Normal

- name: The machine was rebooted 
  moira_trigger:
    name: The machine was rebooted
    target: aliasByNode(DevOps.system.*.uptime.minutes, 2)
    expression: WARN if t1 < 10 else OK
    tags:
      - Moira
      - Info

