- include: firewall.yml

- name: Ansible state path must be created
  file: path={{ ansible_state_path }} state=directory

- name: install EPEL repository config
  yum: name=epel-release state=present 

- name: download Nodesource repository 
  yum: name=https://rpm.nodesource.com/pub_4.x/el/7/x86_64/nodesource-release-el7-1.noarch.rpm state=present

- name: Install dependensies
  yum: name={{ item }} state=present
  with_items:
    - tmux
    - git
    - redis
    - nginx
    - nodejs
    - python-pip

- name: install dependensies for build packages (it is slow)
  yum: name={{ item }} state=present
  with_items:
     - ruby
     - ruby-devel
     - rpmdevtools
  when: build_packages == True 

- name: Install fpm
  gem: name=fpm state=present user_install=no
  when: build_packages == True

- name: Start and enable services
  service: name={{ item }} state=started enabled=yes
  with_items:
    - redis
    - nginx

- name: nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx
