- name: Create directory for Moira Web
  file: path={{ item }} state=directory owner=vagrant group=vagrant
  with_items:
    - "{{ moira_web_path }}"
    - "/home/vagrant/node_modules"

- name: Stop Moira Web
  service: name=moira-web state=stopped
  ignore_errors: yes 

- name: Checkout Moira Web
  git: repo={{ moira_web_repo }} dest={{ moira_web_path }} version={{ moira_web_commit }}
  ignore_errors: yes

- name: Create symlink for node_modules
  file: dest={{ moira_web_path }}/node_modules src=/home/vagrant/node_modules state=link

- name: Moira Web install dependencies (it is slow)
  npm: path={{ moira_web_path }} state=present
  sudo_user: vagrant

- name: nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/moira.conf
  notify: reload nginx

- name: front config
  command: cp "{{ moira_web_path }}/config.json.example" "{{ moira_web_path }}/config.json"

- name: Moira Web create service
  template: src=moira-web.service.j2 dest=/etc/systemd/system/moira-web.service
  notify: update systemd

- name: Start and enable Moira Web service
  service: name=moira-web state=running enabled=true
